SELECT [qid]
      ,[pqid]
      ,[id]
      ,[sid]
      ,[lqid]
      ,[entered]
      ,[brand]
      ,[action]
      ,[request]
      ,[response]
      ,[r1]
      ,[r2]
      ,[r3]
  FROM TABLE_NAME